### ISSUE TITLE
No matching checkpoint file found

### ISSUE THREAD

**Issue by gyc9709** [594422814/TransformerTrack#1]
I run with:
python run_tracker.py trdimp trdimp --sequence Biker

The reported error is :
"No matching checkpoint file found"

How should I repair this?
or How should I set the checkpoint file?

Thanks a lot.

**Comment by 594422814** [comment]
Please download the TrDiMP model and put it in the pytracking/networks folder.
Model link: https://github.com/594422814/TransformerTrack/releases/download/model/trdimp_net.pth.tar

**Comment by gyc9709** [comment]
> Please download the TrDiMP model and put it in the pytracking/networks folder.
> Model link: https://github.com/594422814/TransformerTrack/releases/download/model/trdimp_net.pth.tar

Sorry for bothering again. 
I did as you said, but the error "No matching checkpoint file found" still appeared.
Later I tried to decompression the "trdimp_net.pth.tar" but failed.
Is the model file alright?

**Comment by 594422814** [comment]
Please check the default network path in 'pytracking/evaluation/local.py'. 

Or you can use the absolute path in 'pytracking/parameter/trdimp/trdimp.py', such as 'net_path=your/path/to/TransformerTrack/pytracking/networks/trdimp_net.pth.tar'

**Comment by MJC31** [comment]
"No matching checkpoint file found"



Hi Have you solved this problem?

I encountered the same problem as you, and I tried the above methods but it didn't work.
