### ISSUE TITLE
no matching checkpoint file found

### ISSUE THREAD

**Issue by YanWanquan** [594422814/TransformerTrack#10]
Hi, when I want to run `python run_training dimp transformer_dimp`, it always shows `no matching checkpoint file found`. Does this model need a checkpoint file before training? If yes, where can I download this file? 

When I run to the 52 line of `ltr_trainer.py` file: `for i, data in enumerate(loader,1)`, it shows an error: `out of memory`.   My computer has 16G memory, and my GPU has 32G memory, so I think it is large enough to run the model. Can you give any suggestions about this problem? Thanks.

**Comment by 594422814** [comment]
In the training stage, DiMP uses ResNet for model initialization. Generally, this model will be downloaded by the pytracking framework. Maybe you should check it.
 I use a large batch size of 40 to reduce the training time. If your computer memory is limited, you can set a smaller batch size in the training setting.

**Comment by 594422814** [comment]
In the training stage, DiMP uses ResNet for model initialization. Generally, this model will be downloaded by the pytracking framework. Maybe you should check it.
 I use a large batch size of 40 to reduce the training time. If your computer memory is limited, you can set a smaller batch size in the training setting.

**Comment by Chenlulu1993** [comment]
Which folder do you put the downloaded 'resnet' model in?
