### ISSUE TITLE
what is your hardware for trainning?

### ISSUE THREAD

**Issue by Lightning980729** [594422814/TransformerTrack#11]
what is your hardware for trainning? Super_dimp use one TATIAN X for training. And your traning setting is slight different， I wonder what's the reason。

**Comment by 594422814** [comment]
I train this network using 4 NVIDIA 1080Ti GPUs. It takes about 1 day to finish the training. 
As for the training setting, I increased the batch size to reduce the training time. I also tried other batch sizes (e.g., 24, 36, 40), but I did not observe obvious performance changes.

**Comment by Lightning980729** [comment]
Thanks for your reply. It's really a great job. @594422814
