### ISSUE TITLE
关于测试帧数的问题

### ISSUE THREAD

**Issue by yuyudiandian** [594422814/TransformerTrack#12]
非常感谢作者很棒的工作！但用复现出来的权重文件测试之后，发现大概每秒只有8帧左右可能是什么原因？两张1080ti的显卡。另外想问下作者训练用时多久？

**Comment by YanWanquan** [comment]
> 非常感谢作者很棒的工作！但用复现出来的权重文件测试之后，发现大概每秒只有8帧左右可能是什么原因？两张1080ti的显卡。另外想问下作者训练用时多久？

你好，可以加一下微信吗？我最近也在做这篇文章的复现

**Comment by 594422814** [comment]
我使用OTB-2013中的50个视频估计的tracking速度，我测试了几次，都有20+的FPS。至于速度慢的原因，测试前清空机器中其他任务，机器的CPU可能也会带来一定的速度差异。你也可以尝试跑一下这篇论文的基准方法DiMP，看看你的机器是否达到 DIMP 中的速度。

测试的时候只用一块GPU，训练时候我用4块1080TI GPU进行训练，需要1天（24小时~30小时）左右。

**Comment by yuyudiandian** [comment]
作者你好 请问你的VOT18测试结果是如何得到的，是使用你代码中的run_vot.py么？我尝试使用run_tracker.py测得的vot18结果有问题。能否告诉下我操作步骤，谢谢！

**Comment by 594422814** [comment]
我是使用GOT10k进行VOT的测试的，代码里给出了示例，也可以参考pytracking的README。测试的结果我使用VOT官方的matlab toolkit进行EAO计算

**Comment by yuyudiandian** [comment]
好的谢谢 我去尝试下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月21日(星期五) 上午10:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [594422814/TransformerTrack] 关于测试帧数的问题 (#12)





 
我是使用GOT10k进行VOT的测试的，代码里给出了示例，也可以参考pytracking的README。测试的结果我使用VOT官方的matlab toolkit进行EAO计算
