### ISSUE TITLE
some qusetions on testing VOT18

### ISSUE THREAD

**Issue by yuyudiandian** [594422814/TransformerTrack#14]
when i use GOT10K_VOT.py to test VOT18, some errors will happen in the ./pytracking/tracker/trdimp.py,  it seems some parameters do not match the test of vot18. But i use GOT10K_GOT.py to test GOT_10k, this errors didn't happen, because ./pytracking/tracker/trdimp_for_GOT.py works. Do you have specialied trdimp_for_VOT.py that uses on testing VOT18?
Your prompt attention to my question would be highly appreciated!

**Comment by 594422814** [comment]
No, we just use 'trdimp_for_GOT.py' for all GOT related testing. If you can successfully GOT_10K, it is simple to run VOT using GOT toolkit. They do not have obvious differences. 
Can the GOT10k toolkit find your VOT dataset? Please check the dataset path of VOT2018 and the dataset formats.

**Comment by yuyudiandian** [comment]
Thank you for your reply. This is not the problems of path. I solve this problem in the following progress.
First, i run the GOT10k_VOT.py ,some errors occur:
![72R@8 (TACKD2}A2)IZW (L](https://user-images.githubusercontent.com/71555221/119214799-1f06db00-bafc-11eb-91c0-e11d28584620.png)

It seems like lacking of some parameters, so i look for this parameter "transformer_skipping"in the ./TransformerTrack/pytracking/parameter/trdimp/trdimp_lasot.py in line 31 and line 32 ,but this codes do not exsit in ./TransformerTrack/pytracking/parameter/trdimp/trdimp_vot.py, after i add "params.transformer_skipping = 1e-1 
    params.transformer_memory_size = -1" to trdimp_vot.py, 
![7M BDJ@Y~FR6ILZ8WKS EF0](https://user-images.githubusercontent.com/71555221/119214899-d56ac000-bafc-11eb-90f2-3e6f125a534b.png)

this error doesn't happen. Am i doing this right? Or just code has some bugs on testing VOT2018?

**Comment by 594422814** [comment]
Sorry, I missed these parameters. 
The parameters are: skipping=5, memory_size=20, which are the same as the parameters in other tracking datasets.
Thanks for pointing this issue. I have modified the "trdimp_vot.py"

**Comment by yuyudiandian** [comment]
ok！Thank you！I have tried the “skipping=5, memory_size=20” and “skipping=1e-1, memory_size=-1” ，indeed,&nbsp;the latter does not work as well as the former.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月24日(星期一) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [594422814/TransformerTrack] some qusetions on testing VOT18 (#14)





 
Sorry, I missed these parameters.
 The parameters are: skipping=5, memory_size=20, which are the same as the parameters in other tracking datasets.
 Thanks for pointing this issue. I have modified the "trdimp_vot.py"
