### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by YanWanquan** [594422814/TransformerTrack#15]
In your code I found that you import Lasot, Got10k, TrackingNet and MSCOCOSeq. I want to know if you used all these datasets for training. 

In your paper, you said the batch size you used is 36 image pairs  and there is total 1500 iterations per epoch. However, 1500*36=1,8000 which is much smaller thant the number of images in CoCo dataset.  I remember batch_size * iterations = dataset_sizse. I am a newer in the tracking field, and just a little confused about this. Thanks.

**Comment by 594422814** [comment]
In each epoch, the model uses a fixed size of samples for training instead of utilizing all the training samples. 
The parameters of the code are slightly different from the paper. Please refer to the /ltr/train_settings/

**Comment by QiyuLuo** [comment]
> The parameters of the code are slightly different from the paper. Please refer to the /ltr/train_settings/

Hello, could you please provide a file of the organization format of the data set? I am also new to the field of single target tracking, and I find that these data sets are too large to download all of them. 
I see that your code **only uses a part of the data set** (such as TrackingNet) as the training set sample, can I only just download these? In addition, I see that the sampling sample in your code is each epoch 5W picture, is it the same 5W picture for each round of epoch?
Are the 5W images the same every time you train? If I sampled at random, would the results be very different if I sampled 5W images from different machines? Your early reply will be greatly appreciated.

**Comment by 594422814** [comment]
No, you still need to download all the data of these training sets since the images are randomly chosen. 
You can only use GOT-10K for training and test the performance. As for other datasets, especially the large-scale TrackingNet, I do not have good suggestions. I also downloaded it from the official website.
