### ISSUE TITLE
Training loss

### ISSUE THREAD

**Issue by Tianlu-Zhang** [594422814/TransformerTrack#18]
训练过程中发现bb_ce的loss为负，请问这可能是什么原因造成的？谢谢

![image](https://user-images.githubusercontent.com/48719188/121763281-4ab23980-cb6d-11eb-8dd4-d7fb8a9fa291.png)

**Comment by 594422814** [comment]
基准算法为DiMP系列, 请参考论文“Probabilistic Regression for Visual Tracking”中的loss函数

**Comment by Tianlu-Zhang** [comment]
您的这篇文章使用了Superdimp的训练参数设置，所以本身bb_ce项的loss就会出现负值，并非错误吗？

**Comment by JackjackFan** [comment]
您好，请问您解决了损失为负的问题了吗？还是您确认了本身确实是会负数呢？
