### ISSUE TITLE
some questions on testing

### ISSUE THREAD

**Issue by yuyudiandian** [594422814/TransformerTrack#19]
I did some changes on the structure of code，but when testing GOT or OTB ，it will happen “cuda memory is not enough ”。Same question not happened on testing VOT18，so do you have some suggestions on this question？Or how to reduce the the cuda memory on testing dataset？Thank you.

**Comment by 594422814** [comment]
You can reduce the memory size of the transformer buffer to check whether this issue is solved. However, reducing the memory size may slightly hurt the performance.

**Comment by yuyudiandian** [comment]
Is params.transformer_memory_size?I try to change it ,but it seems doesn't work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月14日(星期一) 晚上8:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [594422814/TransformerTrack] some questions on testing (#19)





 
You can reduce the memory size of the transformer buffer to check whether this issue is solved. However, reducing the memory size may slightly hurt the performance.

**Comment by yuyudiandian** [comment]
ok ，it seems to work.Thank you very much.
