### ISSUE TITLE
Difference between TrSiam and TrDiMP

### ISSUE THREAD

**Issue by YanWanquan** [594422814/TransformerTrack#21]
Hi,

Thanks for your good work! 

When I was reading your paper and your code I found that during the training phase, there is no difference between TrSiam and TrDimp. I want to to know if the difference between thiese two algorithms only occurs during the tracking phase?  For TrSiam,  you also used the DCF during the training phase. Is this true? 

Thanks

**Comment by 594422814** [comment]
Sorry for the late response. TrSiam does not require the DCF. TrSiam is the initialization step of TrDiMP, but they are trained together for convenience. For more details, please refer to the DiMP tracker.

**Comment by Jee-King** [comment]
TrDiMP needs an online update, TrSiam does not require online update. Is it right?

**Comment by 594422814** [comment]
Yes, TrSiam does not update the model in the online tracking process.
