### ISSUE TITLE
Some questions about train setting? 

### ISSUE THREAD

**Issue by yxxxqqq** [594422814/TransformerTrack#3]
Some questions about your baseline? 
It seems that you use the same parameter of SuperDiMP, but not DiMP. Based on the SuperDiMP does achieves the performance described in your paper, but the performance of DiMP is doubtful. However, your paper is elaborated from the perspective of temporal feature, which is novel and great.

**Comment by 594422814** [comment]
Yes, our baseline adopts the "SuperDiMP" setting. 
We worry that "superDiMP" will confuse some readers since it has not been described in published papers. Instead, we add a footnote on page #6, and add more discussions and experiments in the appendix (please refer to A.2 Section and Table 9).
