### ISSUE TITLE
ImportError: Can not compile Precise RoI Pooling library.

### ISSUE THREAD

**Issue by LiShenglana** [594422814/TransformerTrack#38]
I use GPU 3090, cuda 11.3 and met this problem. How can I solve this ? Thank you!

**Comment by Hiyao-yy** [comment]
Have you solved the same problem？

**Comment by LiShenglana** [comment]
I use python 3.7 in the conda environment, and pytorch installed with the following two commands can run this package:
conda install -y pytorch==1.7.1 torchvision==0.8.2 cudatoolkit=11.3 -c pytorch
pip install torch==1.7.1+cu110 --extra-index-url https://download.pytorch.org/whl/cu110

**Comment by LiShenglana** [comment]
> Have you solved the same problem？

I use python 3.7 in the conda environment, and pytorch installed with the following two commands can run this package:
conda install -y pytorch==1.7.1 torchvision==0.8.2 cudatoolkit=11.3 -c pytorch
pip install torch==1.7.1+cu110 --extra-index-url https://download.pytorch.org/whl/cu110

**Comment by Hiyao-yy** [comment]
> Thanks！
